# Generated by Django 5.2 on 2025-05-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading_materials', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readingmaterial',
            old_name='author',
            new_name='author_name',
        ),
        migrations.AddField(
            model_name='readingmaterial',
            name='categories',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='readingmaterial',
            name='cover_image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='readingmaterial',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
