# Generated by Django 5.2 on 2025-05-01 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading_materials', '0002_rename_author_readingmaterial_author_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readingmaterial',
            old_name='average_score',
            new_name='rating',
        ),
    ]
