# Generated by Django 5.2 on 2025-05-01 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading_materials', '0003_rename_average_score_readingmaterial_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readingmaterial',
            old_name='author_name',
            new_name='authorName',
        ),
        migrations.RenameField(
            model_name='readingmaterial',
            old_name='cover_image',
            new_name='coverImage',
        ),
        migrations.RenameField(
            model_name='readingmaterial',
            old_name='publication_date',
            new_name='publicationDate',
        ),
    ]
