# Generated by Django 5.2 on 2025-05-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading_materials', '0004_rename_author_name_readingmaterial_authorname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingmaterial',
            name='isFavorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='readingmaterial',
            name='isFeatured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='readingmaterial',
            name='readingStatus',
            field=models.CharField(default='unread', max_length=50),
        ),
    ]
