# Generated by Django 5.2 on 2025-05-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading_materials', '0005_readingmaterial_isfavorite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.URLField()),
                ('biography', models.TextField()),
                ('popular_books', models.JSONField(default=list)),
            ],
        ),
    ]
