# Generated by Django 5.2 on 2025-05-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.URLField()),
                ('biography', models.TextField()),
                ('popular_books', models.JSONField(default=list)),
            ],
        ),
    ]
