# Generated by Django 5.2 on 2025-05-02 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
